# Generated by Django 2.2.16 on 2022-11-10 06:19

import django.contrib.auth.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221109_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует'}, help_text='Обязательное поле. 150 символов или меньше.Только буквы, цифры или символы @/./+/-/_.Не может быть <me>.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), users.validators.username_not_me_validator], verbose_name='Имя пользователя'),
        ),
    ]
